#!/usr/bin/env python3
"""Headless self-test for the comfyui-dancekit node pack.

Runs without ComfyUI: `server`, `comfy.utils` and `folder_paths` are stubbed, then
every node class is instantiated and its FUNCTION exercised with real fixtures --
a synthetic 128 BPM click track (soundfile) and pose clips generated by dancekit's
own composer. Chains covered:

    Beat Grid -> Compose -> Render -> Save/Load Pose JSON
    Harvest   -> Save/Load Library -> Compose(library)
    Load Pose JSON -> Retime -> Trim(H3)
    SMPL file -> SMPL to OpenPose

Also verifies NODE_CLASS_MAPPINGS coverage, display-name uniqueness, that the JS
LIMB_PAIRS / COLORS tables match dancekit/skeleton.py exactly, and syntax-checks
the JS with `node --check` when node is available.

Usage:  python selftest.py [/path/to/dancekit-repo]
"""

from __future__ import annotations

import asyncio
import ast
import importlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import types
from pathlib import Path

import numpy as np

PACK_DIR = Path(__file__).resolve().parent
TMP = Path(tempfile.mkdtemp(prefix="dancekit_selftest_"))

PASS = 0


def check(cond, msg):
    global PASS
    if not cond:
        raise AssertionError("FAIL: " + msg)
    PASS += 1
    print(f"  ok  {msg}")


# --------------------------------------------------------------------------------------
# 1. Stub ComfyUI modules BEFORE importing the pack
# --------------------------------------------------------------------------------------

class _FakeRoutes:
    def __init__(self):
        self.registered = {}

    def get(self, path):
        def deco(fn):
            self.registered[("GET", path)] = fn
            return fn
        return deco

    def post(self, path):
        def deco(fn):
            self.registered[("POST", path)] = fn
            return fn
        return deco


fake_server = types.ModuleType("server")


class _FakePromptServer:
    pass


_FakePromptServer.instance = _FakePromptServer()
_FakePromptServer.instance.routes = _FakeRoutes()
fake_server.PromptServer = _FakePromptServer
sys.modules["server"] = fake_server

fake_comfy = types.ModuleType("comfy")
fake_comfy_utils = types.ModuleType("comfy.utils")


class _FakeProgressBar:
    def __init__(self, total):
        self.total, self.current = total, 0

    def update(self, n=1):
        self.current += n

    def update_absolute(self, value, total=None, preview=None):
        self.current = value


fake_comfy_utils.ProgressBar = _FakeProgressBar
fake_comfy.utils = fake_comfy_utils
sys.modules["comfy"] = fake_comfy
sys.modules["comfy.utils"] = fake_comfy_utils

fake_folder_paths = types.ModuleType("folder_paths")
fake_folder_paths.get_output_directory = lambda: str(TMP / "output")
sys.modules["folder_paths"] = fake_folder_paths

# --------------------------------------------------------------------------------------
# 2. Make dancekit importable (simulates `pip install -e dancekit`)
# --------------------------------------------------------------------------------------

dk_repo = Path(sys.argv[1]) if len(sys.argv) > 1 else PACK_DIR.parent / "dancekit"
if (dk_repo / "dancekit" / "__init__.py").is_file():
    sys.path.insert(0, str(dk_repo))

# Import the pack as ComfyUI would (directory name with a hyphen is fine here).
sys.path.insert(0, str(PACK_DIR.parent))
pack = importlib.import_module(PACK_DIR.name)

print("== module imports ==")
check(hasattr(pack, "NODE_CLASS_MAPPINGS"), "pack exposes NODE_CLASS_MAPPINGS")
check(hasattr(pack, "WEB_DIRECTORY"), "pack exposes WEB_DIRECTORY")

nodes_pkg = importlib.import_module(PACK_DIR.name + ".nodes")
_dk = importlib.import_module(PACK_DIR.name + ".nodes._dk")
server_routes = importlib.import_module(PACK_DIR.name + ".nodes.server_routes")
import dancekit.skeleton as dk_skeleton  # noqa: E402

M = pack.NODE_CLASS_MAPPINGS
D = pack.NODE_DISPLAY_NAME_MAPPINGS

EXPECTED = [
    "DKBeatGrid", "DKCompose", "DKHarvest", "DKSaveLibrary", "DKLoadLibrary",
    "DKLoadPoseJSON", "DKSavePoseJSON", "DKRetime", "DKSMPLToOpenPose",
    "DKRenderSkeleton", "DKPoseInfo", "DKTrim",
]
check(sorted(M) == sorted(EXPECTED), f"all {len(EXPECTED)} nodes registered")
check(sorted(D) == sorted(EXPECTED), "display names cover every node")
check(len(set(D.values())) == len(D), "display names are unique")
for name, cls in M.items():
    check(callable(getattr(cls, cls.FUNCTION, None)), f"{name}.FUNCTION resolves")
    check(cls.CATEGORY == "dancekit", f"{name}.CATEGORY == 'dancekit'")
    spec = cls.INPUT_TYPES()
    check(isinstance(spec, dict) and "required" in spec, f"{name}.INPUT_TYPES valid")
    for sect in ("required", "optional"):
        for wname, wdef in (spec.get(sect) or {}).items():
            if isinstance(wdef, tuple) and len(wdef) > 1 and isinstance(wdef[1], dict):
                if wdef[0] in ("FLOAT", "INT", "BOOLEAN", "STRING") or isinstance(wdef[0], list):
                    # every adjustable widget except bare passthrough sockets
                    if wname not in ("pose", "beat_grid", "library", "audio"):
                        assert "tooltip" in wdef[1], f"{name}.{wname} missing tooltip"
check(True, "every adjustable widget carries a native tooltip")

# --------------------------------------------------------------------------------------
# 3. Fixtures: synthetic 128 BPM click track + pose JSON clips
# --------------------------------------------------------------------------------------

print("== fixtures ==")
import soundfile as sf  # noqa: E402

SR = 22050
BPM = 128.0
DUR = 20.0


def click_track(path: Path):
    n = int(DUR * SR)
    y = np.zeros(n, dtype=np.float32)
    spb = 60.0 / BPM
    t_kick = np.arange(0, DUR, spb)                    # kick every beat
    for i, tb in enumerate(t_kick):
        s = int(tb * SR)
        seg = np.arange(min(int(0.09 * SR), n - s))
        env = np.exp(-seg / (0.02 * SR))
        f = 110 * np.exp(-seg / (0.015 * SR)) + 45
        amp = 1.35 if i % 4 == 0 else 0.8              # louder kick on the downbeat
        y[s:s + len(seg)] += amp * env * np.sin(2 * np.pi * np.cumsum(f) / SR)
    rng = np.random.default_rng(0)
    for tb in np.arange(spb, DUR, 2 * spb):            # snare on 2 and 4
        s = int(tb * SR)
        seg = min(int(0.05 * SR), n - s)
        y[s:s + seg] += 0.5 * rng.standard_normal(seg).astype(np.float32) * \
            np.exp(-np.arange(seg) / (0.008 * SR))
    for tb in np.arange(0, DUR, spb / 2):              # hats on eighths
        s = int(tb * SR)
        seg = min(int(0.02 * SR), n - s)
        y[s:s + seg] += 0.15 * rng.standard_normal(seg).astype(np.float32) * \
            np.exp(-np.arange(seg) / (0.003 * SR))
    y /= max(np.abs(y).max(), 1e-9)
    sf.write(str(path), y, SR)


song = TMP / "click128.wav"
click_track(song)
check(song.stat().st_size > 100000, f"click track written ({song})")

# Pose clips for harvesting: composed against synthetic grids with different seeds.
from dancekit import beatgrid as dk_beatgrid, compose as dk_compose, poseio  # noqa: E402

clips_dir = TMP / "clips"
clips_dir.mkdir()
for seed in (1, 2):
    g = dk_beatgrid.synthetic(120.0, 12.0)
    p, _ = dk_compose.compose(g, fps=30.0, seed=seed, subdivision=1)
    poseio.save_pose_json(clips_dir / f"clip{seed}.json", p,
                          {"canvas_width": 832, "canvas_height": 1472})
check(len(list(clips_dir.glob("*.json"))) == 2, "two pose-JSON clips generated")

# SMPL motion fixture: smooth random (T,24,3) joint track.
rng = np.random.default_rng(3)
T_smpl = 60
base = rng.standard_normal((1, 24, 3)) * 0.3
wob = np.sin(np.linspace(0, 4 * np.pi, T_smpl))[:, None, None]
joints = base + 0.15 * wob * rng.standard_normal((1, 24, 3))
smpl_path = TMP / "motion.npy"
np.save(smpl_path, joints.astype(np.float32))

# --------------------------------------------------------------------------------------
# 4. Node chain: Beat Grid -> Compose -> Render -> Save/Load Pose JSON
# --------------------------------------------------------------------------------------

print("== chain: beat grid -> compose -> render -> save/load ==")
import torch  # noqa: E402

bg_node = M["DKBeatGrid"]()
grid, report = bg_node.analyse(
    audio_path=str(song), bpm=0.0, tightness=100.0, offset=0.0, beats_per_bar=4,
    downbeat_index=-1, rigid=True, auto_align=True, trim_silence=False,
    unique_id="bg1")
check(abs(grid.tempo - BPM) < 1.0, f"tempo recovered: {grid.tempo:.2f} (~{BPM})")
check(len(grid.beats) >= 38, f"{len(grid.beats)} beats over {DUR}s")
check(float(grid.downbeats[0]) < 60.0 / BPM, "first downbeat is beat 1 (kick phase)")
check("tempo" in report and "downbeat" in report, "beat grid report string populated")

# AUDIO input path (ComfyUI LoadAudio-style dict)
wav, _ = sf.read(str(song), dtype="float32")
audio_in = {"waveform": torch.from_numpy(wav)[None, None, :], "sample_rate": SR}
grid2, _ = bg_node.analyse(
    audio_path="", bpm=0.0, tightness=100.0, offset=0.0, beats_per_bar=4,
    downbeat_index=-1, rigid=True, auto_align=True, trim_silence=False,
    audio=audio_in, unique_id="bg2")
check(abs(grid2.tempo - grid.tempo) < 0.5, "AUDIO input path matches file path")

comp_node = M["DKCompose"]()
dkpose, info = comp_node.run(
    beat_grid=grid, fps=24.0, subdivision=1, phrase_beats=8, sections=3, seed=7,
    snap=0.65, overshoot=0.12, variation=0.5, bounce=0.012, max_seconds=0.0,
    unique_id="42")
pose_arr = dkpose["pose"]
check(pose_arr.ndim == 3 and pose_arr.shape[1:] == (18, 3),
      f"compose pose shape {pose_arr.shape}")
check(dkpose["fps"] == 24.0 and dkpose["grid"] is grid, "DK_POSE carries fps + grid")
check(json.loads(info)["tempo"] > 0, "compose info is valid JSON")
check("42" in _dk.POSE_CACHE and _dk.POSE_CACHE["42"]["beats"] is not None,
      "compose cached preview with beat times under its node id")

rn = M["DKRenderSkeleton"]()
(images,) = rn.run(pose=dkpose, width=128, height=224, thickness=1.0, unique_id="43")
check(isinstance(images, torch.Tensor), "render returns a torch tensor")
check(images.dtype == torch.float32, "render dtype float32")
check(images.shape == (pose_arr.shape[0], 224, 128, 3),
      f"render shape (B,H,W,C) = {tuple(images.shape)}")
check(float(images.min()) >= 0.0 and float(images.max()) <= 1.0, "render range 0..1")
check(float(images.max()) > 0.2, "render actually drew a skeleton")

sv = M["DKSavePoseJSON"]()
(saved_path,) = sv.run(pose=dkpose, path="dancekit/pose.json",
                       canvas_width=832, canvas_height=1472, normalised=True)
check(Path(saved_path).is_file(), f"pose JSON saved to output dir ({saved_path})")
check(str(TMP / "output") in saved_path, "relative save path resolved via folder_paths")

ld = M["DKLoadPoseJSON"]()
dkpose2, nframes, _info = ld.run(path=saved_path, fps=24.0, person=-1, unique_id="44")
check(nframes == pose_arr.shape[0], "pose JSON round trip preserves frame count")
check(np.allclose(dkpose2["pose"][:, :, :2], pose_arr[:, :, :2], atol=1e-4),
      "pose JSON round trip preserves coordinates")

# --------------------------------------------------------------------------------------
# 5. Chain: Harvest -> Save/Load Library -> Compose(library)
# --------------------------------------------------------------------------------------

print("== chain: harvest -> library -> compose ==")
hv = M["DKHarvest"]()
dklib, sheet, manifest = hv.run(
    source_path=str(clips_dir), prominence=0.12, min_gap=0.10, conf=0.3,
    foreshorten=0.6, max_poses=16, min_distance=0.30, drop_neutral=0.18,
    min_count=1, mirror_invariant=True, skip_slowmo=False, src_fps=0.0,
    dropped="", unique_id="50")
check(len(dklib["lib"]) >= 4, f"harvest built a vocabulary ({len(dklib['lib'])} poses)")
check(all(not n.endswith("_m") for n in dklib["lib"]), "DK_LIBRARY stores base poses only")
check(isinstance(sheet, torch.Tensor) and sheet.dtype == torch.float32
      and sheet.ndim == 4 and sheet.shape[0] == 1 and sheet.shape[-1] == 3,
      f"contact sheet IMAGE tensor {tuple(sheet.shape)}")
check(0.0 <= float(sheet.min()) and float(sheet.max()) <= 1.0, "contact sheet range 0..1")
man = json.loads(manifest)
check(man["poses"] == len(dklib["lib"]) and len(man["sources"]) == 2,
      "manifest reports poses + per-source stats")
check("50" in _dk.LIBRARY_CACHE, "harvest cached library under its node id")

# dropped-pose exclusion (library browser writes this widget)
dklib_dropped, _, man2 = hv.run(
    source_path=str(clips_dir), prominence=0.12, min_gap=0.10, conf=0.3,
    foreshorten=0.6, max_poses=16, min_distance=0.30, drop_neutral=0.18,
    min_count=1, mirror_invariant=True, skip_slowmo=False, src_fps=0.0,
    dropped='["h00", "h01"]', unique_id="51")
check("h00" not in dklib_dropped["lib"] and "h01" not in dklib_dropped["lib"]
      and len(dklib_dropped["lib"]) == len(dklib["lib"]) - 2,
      "dropped widget excludes poses on the next run")

slb = M["DKSaveLibrary"]()
(lib_path,) = slb.run(library=dklib, path=str(TMP / "vocab.npz"))
check(Path(lib_path).is_file(), "library saved to .npz")

llb = M["DKLoadLibrary"]()
dklib2, summary = llb.run(path=lib_path, dropped="", unique_id="52")
check(sorted(dklib2["lib"]) == sorted(dklib["lib"]), "library npz round trip")
check(dklib2["energy_map"] is not None, "loaded library carries energies")
dklib3, _ = llb.run(path=lib_path, dropped='["h02"]', unique_id="53")
check("h02" not in dklib3["lib"], "load-library dropped widget works")

dkpose_lib, info_lib = comp_node.run(
    beat_grid=grid, fps=24.0, subdivision=2, phrase_beats=8, sections=2, seed=1,
    snap=0.5, overshoot=0.2, variation=0.5, bounce=0.012, max_seconds=8.0,
    library=dklib2, unique_id="54")
check(dkpose_lib["pose"].shape[0] <= int(8.0 * 24) + 2,
      "compose with harvested library + max_seconds works")

# --------------------------------------------------------------------------------------
# 6. Retime, SMPL, Trim, Pose Info
# --------------------------------------------------------------------------------------

print("== retime / smpl / trim / info ==")
src_pose, _, _ = ld.run(path=str(clips_dir / "clip1.json"), fps=30.0, person=-1,
                        unique_id="60")
rt = M["DKRetime"]()
retimed, rt_info = rt.run(
    pose=src_pose, beat_grid=grid, src_fps=0.0, prominence=0.15, min_gap=0.12,
    max_keyposes=0, subdivision=1, stride=1, start_index=0, mode="sequential",
    snap=0.7, overshoot=0.0, root_damping=0.2, loop=False, out_fps=24.0,
    unique_id="61")
check(retimed["pose"].shape[1:] == (18, 3) and retimed["fps"] == 24.0,
      f"retime output {retimed['pose'].shape} @24fps")
check(json.loads(rt_info)["anchors"] >= 2, "retime found anchors")
retimed_loop, _ = rt.run(
    pose=src_pose, beat_grid=grid, src_fps=30.0, prominence=0.15, min_gap=0.12,
    max_keyposes=0, subdivision=1, stride=1, start_index=0, mode="nearest",
    snap=0.7, overshoot=0.1, root_damping=0.0, loop=True, out_fps=24.0,
    unique_id="62")
check(retimed_loop["pose"].shape[0] >= retimed["pose"].shape[0],
      "loop mode covers at least as much of the song")

sm = M["DKSMPLToOpenPose"]()
smpl_pose, smpl_info = sm.run(motion_path=str(smpl_path), fps=30.0, azimuth=15.0,
                              elevation=5.0, up_axis="y", headroom=0.10, floor=0.04,
                              unique_id="63")
check(smpl_pose["pose"].shape == (T_smpl, 18, 3), "SMPL projection shape")
check(float(np.nanmax(smpl_pose["pose"][:, :, :2])) <= 1.5
      and float(np.nanmin(smpl_pose["pose"][:, :, :2])) >= -0.5,
      "SMPL projection lands on the canvas")

tr = M["DKTrim"]()
trimmed, n1, ti1 = tr.run(pose=dkpose, target_frames=100, start_frame=0,
                          pad_mode="hold", h3_frame_grid=True, unique_id="64")
check(n1 == 107 and n1 % 17 == 5, f"H3 snap 100 -> {n1} (frames % 17 == 5)")
trimmed2, n2, _ = tr.run(pose=dkpose, target_frames=60, start_frame=0,
                         pad_mode="hold", h3_frame_grid=True, unique_id="65")
check(n2 == 56, f"H3 snap 60 -> {n2}")
short = {"pose": dkpose["pose"][:30], "fps": 24.0, "meta": {}, "grid": grid}
looped, n3, _ = tr.run(pose=short, target_frames=90, start_frame=0,
                       pad_mode="loop", h3_frame_grid=False, unique_id="66")
check(n3 == 90 and np.allclose(looped["pose"][0], looped["pose"][30]),
      "loop padding repeats the sequence")

pi = M["DKPoseInfo"]()
(pi_report,) = pi.run(pose=dkpose, prominence=0.15, min_gap=0.12)
check("keyposes" in pi_report and "slow-mo" in pi_report, "pose info report populated")

# --------------------------------------------------------------------------------------
# 7. Server routes (against the stub PromptServer) + payloads
# --------------------------------------------------------------------------------------

print("== server routes ==")
registered = fake_server.PromptServer.instance.routes.registered
try:
    import aiohttp  # noqa: F401
    have_aiohttp = True
except ImportError:
    have_aiohttp = False

if have_aiohttp:
    ok = server_routes.register_routes()
    check(ok, "routes registered against stub PromptServer")
    check(("GET", "/dancekit/pose") in registered
          and ("GET", "/dancekit/library") in registered
          and ("POST", "/dancekit/clear") in registered, "all three routes present")

    class _Req:
        def __init__(self, **q):
            self.rel_url = types.SimpleNamespace(query=q)

    resp = asyncio.run(registered[("GET", "/dancekit/pose")](_Req(node_id="42")))
    body = json.loads(resp.body.decode())
    check(body["count"] == pose_arr.shape[0] and len(body["frames"]) == body["count"]
          and len(body["frames"][0]) == 18 and len(body["beats"]) == len(grid.beats),
          "/dancekit/pose payload: frames + fps + beats/downbeats")
    resp = asyncio.run(registered[("GET", "/dancekit/library")](_Req(node_id="50")))
    body = json.loads(resp.body.decode())
    check(sorted(body["names"]) == sorted(dklib["lib"])
          and all(len(body["poses"][n]) == 18 for n in body["names"]),
          "/dancekit/library payload from cache")
    resp = asyncio.run(registered[("GET", "/dancekit/library")](
        _Req(node_id="nope", path=lib_path)))
    body = json.loads(resp.body.decode())
    check(sorted(body["names"]) == sorted(dklib["lib"]),
          "/dancekit/library falls back to reading the .npz by path")
    resp = asyncio.run(registered[("GET", "/dancekit/pose")](_Req(node_id="nope")))
    check(resp.status == 404, "/dancekit/pose 404s for unknown node ids")
else:
    payload = server_routes._pose_payload(_dk.POSE_CACHE["42"])
    check(payload["count"] == pose_arr.shape[0] and "beats" in payload,
          "pose payload builds (aiohttp absent; route registration untested)")
    lp = server_routes._library_payload(dklib["lib"], dklib["meta"])
    check(sorted(lp["names"]) == sorted(dklib["lib"]), "library payload builds")

# --------------------------------------------------------------------------------------
# 8. JS: syntax check + LIMB_PAIRS / COLORS must match dancekit/skeleton.py
# --------------------------------------------------------------------------------------

print("== frontend ==")
js_files = sorted((PACK_DIR / "web" / "js").glob("*.js"))
check(len(js_files) >= 1, f"web/js contains {len(js_files)} file(s)")

node_bin = shutil.which("node")
if node_bin:
    for js in js_files:
        r = subprocess.run([node_bin, "--check", str(js)], capture_output=True, text=True)
        check(r.returncode == 0, f"node --check {js.name}" +
              ("" if r.returncode == 0 else f": {r.stderr}"))
else:
    print("  --  node not on PATH; JS syntax check skipped here (run node --check)")

js_text = (PACK_DIR / "web" / "js" / "dancekit.js").read_text()


def _parse_js_array(name):
    m = re.search(rf"const {name}\s*=\s*(\[[^;]*?\]);", js_text, re.S)
    assert m, f"{name} not found in dancekit.js"
    return ast.literal_eval(m.group(1))


js_pairs = [tuple(p) for p in _parse_js_array("LIMB_PAIRS")]
js_colors = [tuple(c) for c in _parse_js_array("COLORS")]
check(js_pairs == [tuple(p) for p in dk_skeleton.LIMB_PAIRS],
      "JS LIMB_PAIRS matches dancekit/skeleton.py exactly")
check(js_colors == [tuple(c) for c in dk_skeleton.COLORS],
      "JS COLORS matches dancekit/skeleton.py exactly")
check(str(len(dk_skeleton.JOINT_NAMES)) == "18" and "j < 18" in js_text,
      "JS draws all 18 joints")

print(f"\nALL {PASS} CHECKS PASSED")
